// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system.proto

package rsctrl.system;

public final class System {
  private System() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum RequestMsgIds
      implements com.google.protobuf.ProtocolMessageEnum {
    MsgId_RequestSystemStatus(0, 1),
    ;
    
    public static final int MsgId_RequestSystemStatus_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static RequestMsgIds valueOf(int value) {
      switch (value) {
        case 1: return MsgId_RequestSystemStatus;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RequestMsgIds>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestMsgIds>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestMsgIds>() {
            public RequestMsgIds findValueByNumber(int number) {
              return RequestMsgIds.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return rsctrl.system.System.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final RequestMsgIds[] VALUES = {
      MsgId_RequestSystemStatus, 
    };
    
    public static RequestMsgIds valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RequestMsgIds(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:rsctrl.system.RequestMsgIds)
  }
  
  public enum ResponseMsgIds
      implements com.google.protobuf.ProtocolMessageEnum {
    MsgId_ResponseSystemStatus(0, 1),
    ;
    
    public static final int MsgId_ResponseSystemStatus_VALUE = 1;
    
    
    public final int getNumber() { return value; }
    
    public static ResponseMsgIds valueOf(int value) {
      switch (value) {
        case 1: return MsgId_ResponseSystemStatus;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ResponseMsgIds>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ResponseMsgIds>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseMsgIds>() {
            public ResponseMsgIds findValueByNumber(int number) {
              return ResponseMsgIds.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return rsctrl.system.System.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final ResponseMsgIds[] VALUES = {
      MsgId_ResponseSystemStatus, 
    };
    
    public static ResponseMsgIds valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private ResponseMsgIds(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:rsctrl.system.ResponseMsgIds)
  }
  
  public interface RequestSystemStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class RequestSystemStatus extends
      com.google.protobuf.GeneratedMessage
      implements RequestSystemStatusOrBuilder {
    // Use RequestSystemStatus.newBuilder() to construct.
    private RequestSystemStatus(Builder builder) {
      super(builder);
    }
    private RequestSystemStatus(boolean noInit) {}
    
    private static final RequestSystemStatus defaultInstance;
    public static RequestSystemStatus getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestSystemStatus getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rsctrl.system.System.internal_static_rsctrl_system_RequestSystemStatus_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rsctrl.system.System.internal_static_rsctrl_system_RequestSystemStatus_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rsctrl.system.System.RequestSystemStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rsctrl.system.System.RequestSystemStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rsctrl.system.System.RequestSystemStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rsctrl.system.System.RequestSystemStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rsctrl.system.System.RequestSystemStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rsctrl.system.System.internal_static_rsctrl_system_RequestSystemStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rsctrl.system.System.internal_static_rsctrl_system_RequestSystemStatus_fieldAccessorTable;
      }
      
      // Construct using rsctrl.system.System.RequestSystemStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rsctrl.system.System.RequestSystemStatus.getDescriptor();
      }
      
      public rsctrl.system.System.RequestSystemStatus getDefaultInstanceForType() {
        return rsctrl.system.System.RequestSystemStatus.getDefaultInstance();
      }
      
      public rsctrl.system.System.RequestSystemStatus build() {
        rsctrl.system.System.RequestSystemStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rsctrl.system.System.RequestSystemStatus buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rsctrl.system.System.RequestSystemStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rsctrl.system.System.RequestSystemStatus buildPartial() {
        rsctrl.system.System.RequestSystemStatus result = new rsctrl.system.System.RequestSystemStatus(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rsctrl.system.System.RequestSystemStatus) {
          return mergeFrom((rsctrl.system.System.RequestSystemStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rsctrl.system.System.RequestSystemStatus other) {
        if (other == rsctrl.system.System.RequestSystemStatus.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:rsctrl.system.RequestSystemStatus)
    }
    
    static {
      defaultInstance = new RequestSystemStatus(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rsctrl.system.RequestSystemStatus)
  }
  
  public interface ResponseSystemStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .rsctrl.core.Status status = 1;
    boolean hasStatus();
    rsctrl.core.Core.Status getStatus();
    rsctrl.core.Core.StatusOrBuilder getStatusOrBuilder();
    
    // required uint32 no_peers = 2;
    boolean hasNoPeers();
    int getNoPeers();
    
    // required uint32 no_connected = 3;
    boolean hasNoConnected();
    int getNoConnected();
    
    // required .rsctrl.system.ResponseSystemStatus.NetCode net_status = 4;
    boolean hasNetStatus();
    rsctrl.system.System.ResponseSystemStatus.NetCode getNetStatus();
    
    // required .rsctrl.core.Bandwidth bw_total = 5;
    boolean hasBwTotal();
    rsctrl.core.Core.Bandwidth getBwTotal();
    rsctrl.core.Core.BandwidthOrBuilder getBwTotalOrBuilder();
  }
  public static final class ResponseSystemStatus extends
      com.google.protobuf.GeneratedMessage
      implements ResponseSystemStatusOrBuilder {
    // Use ResponseSystemStatus.newBuilder() to construct.
    private ResponseSystemStatus(Builder builder) {
      super(builder);
    }
    private ResponseSystemStatus(boolean noInit) {}
    
    private static final ResponseSystemStatus defaultInstance;
    public static ResponseSystemStatus getDefaultInstance() {
      return defaultInstance;
    }
    
    public ResponseSystemStatus getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rsctrl.system.System.internal_static_rsctrl_system_ResponseSystemStatus_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rsctrl.system.System.internal_static_rsctrl_system_ResponseSystemStatus_fieldAccessorTable;
    }
    
    public enum NetCode
        implements com.google.protobuf.ProtocolMessageEnum {
      BAD_UNKNOWN(0, 0),
      BAD_OFFLINE(1, 1),
      BAD_NATSYM(2, 2),
      BAD_NODHT_NAT(3, 3),
      WARNING_RESTART(4, 4),
      WARNING_NATTED(5, 5),
      WARNING_NODHT(6, 6),
      GOOD(7, 7),
      ADV_FORWARD(8, 8),
      ;
      
      public static final int BAD_UNKNOWN_VALUE = 0;
      public static final int BAD_OFFLINE_VALUE = 1;
      public static final int BAD_NATSYM_VALUE = 2;
      public static final int BAD_NODHT_NAT_VALUE = 3;
      public static final int WARNING_RESTART_VALUE = 4;
      public static final int WARNING_NATTED_VALUE = 5;
      public static final int WARNING_NODHT_VALUE = 6;
      public static final int GOOD_VALUE = 7;
      public static final int ADV_FORWARD_VALUE = 8;
      
      
      public final int getNumber() { return value; }
      
      public static NetCode valueOf(int value) {
        switch (value) {
          case 0: return BAD_UNKNOWN;
          case 1: return BAD_OFFLINE;
          case 2: return BAD_NATSYM;
          case 3: return BAD_NODHT_NAT;
          case 4: return WARNING_RESTART;
          case 5: return WARNING_NATTED;
          case 6: return WARNING_NODHT;
          case 7: return GOOD;
          case 8: return ADV_FORWARD;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<NetCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NetCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NetCode>() {
              public NetCode findValueByNumber(int number) {
                return NetCode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return rsctrl.system.System.ResponseSystemStatus.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final NetCode[] VALUES = {
        BAD_UNKNOWN, BAD_OFFLINE, BAD_NATSYM, BAD_NODHT_NAT, WARNING_RESTART, WARNING_NATTED, WARNING_NODHT, GOOD, ADV_FORWARD, 
      };
      
      public static NetCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private NetCode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:rsctrl.system.ResponseSystemStatus.NetCode)
    }
    
    private int bitField0_;
    // required .rsctrl.core.Status status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private rsctrl.core.Core.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public rsctrl.core.Core.Status getStatus() {
      return status_;
    }
    public rsctrl.core.Core.StatusOrBuilder getStatusOrBuilder() {
      return status_;
    }
    
    // required uint32 no_peers = 2;
    public static final int NO_PEERS_FIELD_NUMBER = 2;
    private int noPeers_;
    public boolean hasNoPeers() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getNoPeers() {
      return noPeers_;
    }
    
    // required uint32 no_connected = 3;
    public static final int NO_CONNECTED_FIELD_NUMBER = 3;
    private int noConnected_;
    public boolean hasNoConnected() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNoConnected() {
      return noConnected_;
    }
    
    // required .rsctrl.system.ResponseSystemStatus.NetCode net_status = 4;
    public static final int NET_STATUS_FIELD_NUMBER = 4;
    private rsctrl.system.System.ResponseSystemStatus.NetCode netStatus_;
    public boolean hasNetStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public rsctrl.system.System.ResponseSystemStatus.NetCode getNetStatus() {
      return netStatus_;
    }
    
    // required .rsctrl.core.Bandwidth bw_total = 5;
    public static final int BW_TOTAL_FIELD_NUMBER = 5;
    private rsctrl.core.Core.Bandwidth bwTotal_;
    public boolean hasBwTotal() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public rsctrl.core.Core.Bandwidth getBwTotal() {
      return bwTotal_;
    }
    public rsctrl.core.Core.BandwidthOrBuilder getBwTotalOrBuilder() {
      return bwTotal_;
    }
    
    private void initFields() {
      status_ = rsctrl.core.Core.Status.getDefaultInstance();
      noPeers_ = 0;
      noConnected_ = 0;
      netStatus_ = rsctrl.system.System.ResponseSystemStatus.NetCode.BAD_UNKNOWN;
      bwTotal_ = rsctrl.core.Core.Bandwidth.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNoPeers()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNoConnected()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNetStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBwTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getStatus().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBwTotal().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, noPeers_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, noConnected_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, netStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, bwTotal_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, status_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, noPeers_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, noConnected_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, netStatus_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, bwTotal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rsctrl.system.System.ResponseSystemStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rsctrl.system.System.ResponseSystemStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rsctrl.system.System.ResponseSystemStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rsctrl.system.System.ResponseSystemStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rsctrl.system.System.internal_static_rsctrl_system_ResponseSystemStatus_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rsctrl.system.System.internal_static_rsctrl_system_ResponseSystemStatus_fieldAccessorTable;
      }
      
      // Construct using rsctrl.system.System.ResponseSystemStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
          getBwTotalFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (statusBuilder_ == null) {
          status_ = rsctrl.core.Core.Status.getDefaultInstance();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        noPeers_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        noConnected_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        netStatus_ = rsctrl.system.System.ResponseSystemStatus.NetCode.BAD_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (bwTotalBuilder_ == null) {
          bwTotal_ = rsctrl.core.Core.Bandwidth.getDefaultInstance();
        } else {
          bwTotalBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rsctrl.system.System.ResponseSystemStatus.getDescriptor();
      }
      
      public rsctrl.system.System.ResponseSystemStatus getDefaultInstanceForType() {
        return rsctrl.system.System.ResponseSystemStatus.getDefaultInstance();
      }
      
      public rsctrl.system.System.ResponseSystemStatus build() {
        rsctrl.system.System.ResponseSystemStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rsctrl.system.System.ResponseSystemStatus buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rsctrl.system.System.ResponseSystemStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rsctrl.system.System.ResponseSystemStatus buildPartial() {
        rsctrl.system.System.ResponseSystemStatus result = new rsctrl.system.System.ResponseSystemStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.noPeers_ = noPeers_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.noConnected_ = noConnected_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.netStatus_ = netStatus_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (bwTotalBuilder_ == null) {
          result.bwTotal_ = bwTotal_;
        } else {
          result.bwTotal_ = bwTotalBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rsctrl.system.System.ResponseSystemStatus) {
          return mergeFrom((rsctrl.system.System.ResponseSystemStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rsctrl.system.System.ResponseSystemStatus other) {
        if (other == rsctrl.system.System.ResponseSystemStatus.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        if (other.hasNoPeers()) {
          setNoPeers(other.getNoPeers());
        }
        if (other.hasNoConnected()) {
          setNoConnected(other.getNoConnected());
        }
        if (other.hasNetStatus()) {
          setNetStatus(other.getNetStatus());
        }
        if (other.hasBwTotal()) {
          mergeBwTotal(other.getBwTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        if (!hasNoPeers()) {
          
          return false;
        }
        if (!hasNoConnected()) {
          
          return false;
        }
        if (!hasNetStatus()) {
          
          return false;
        }
        if (!hasBwTotal()) {
          
          return false;
        }
        if (!getStatus().isInitialized()) {
          
          return false;
        }
        if (!getBwTotal().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              rsctrl.core.Core.Status.Builder subBuilder = rsctrl.core.Core.Status.newBuilder();
              if (hasStatus()) {
                subBuilder.mergeFrom(getStatus());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setStatus(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              noPeers_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              noConnected_ = input.readUInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              rsctrl.system.System.ResponseSystemStatus.NetCode value = rsctrl.system.System.ResponseSystemStatus.NetCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                netStatus_ = value;
              }
              break;
            }
            case 42: {
              rsctrl.core.Core.Bandwidth.Builder subBuilder = rsctrl.core.Core.Bandwidth.newBuilder();
              if (hasBwTotal()) {
                subBuilder.mergeFrom(getBwTotal());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBwTotal(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .rsctrl.core.Status status = 1;
      private rsctrl.core.Core.Status status_ = rsctrl.core.Core.Status.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rsctrl.core.Core.Status, rsctrl.core.Core.Status.Builder, rsctrl.core.Core.StatusOrBuilder> statusBuilder_;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public rsctrl.core.Core.Status getStatus() {
        if (statusBuilder_ == null) {
          return status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      public Builder setStatus(rsctrl.core.Core.Status value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setStatus(
          rsctrl.core.Core.Status.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeStatus(rsctrl.core.Core.Status value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              status_ != rsctrl.core.Core.Status.getDefaultInstance()) {
            status_ =
              rsctrl.core.Core.Status.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = rsctrl.core.Core.Status.getDefaultInstance();
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public rsctrl.core.Core.Status.Builder getStatusBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      public rsctrl.core.Core.StatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rsctrl.core.Core.Status, rsctrl.core.Core.Status.Builder, rsctrl.core.Core.StatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rsctrl.core.Core.Status, rsctrl.core.Core.Status.Builder, rsctrl.core.Core.StatusOrBuilder>(
                  status_,
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }
      
      // required uint32 no_peers = 2;
      private int noPeers_ ;
      public boolean hasNoPeers() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getNoPeers() {
        return noPeers_;
      }
      public Builder setNoPeers(int value) {
        bitField0_ |= 0x00000002;
        noPeers_ = value;
        onChanged();
        return this;
      }
      public Builder clearNoPeers() {
        bitField0_ = (bitField0_ & ~0x00000002);
        noPeers_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 no_connected = 3;
      private int noConnected_ ;
      public boolean hasNoConnected() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNoConnected() {
        return noConnected_;
      }
      public Builder setNoConnected(int value) {
        bitField0_ |= 0x00000004;
        noConnected_ = value;
        onChanged();
        return this;
      }
      public Builder clearNoConnected() {
        bitField0_ = (bitField0_ & ~0x00000004);
        noConnected_ = 0;
        onChanged();
        return this;
      }
      
      // required .rsctrl.system.ResponseSystemStatus.NetCode net_status = 4;
      private rsctrl.system.System.ResponseSystemStatus.NetCode netStatus_ = rsctrl.system.System.ResponseSystemStatus.NetCode.BAD_UNKNOWN;
      public boolean hasNetStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public rsctrl.system.System.ResponseSystemStatus.NetCode getNetStatus() {
        return netStatus_;
      }
      public Builder setNetStatus(rsctrl.system.System.ResponseSystemStatus.NetCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        netStatus_ = value;
        onChanged();
        return this;
      }
      public Builder clearNetStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        netStatus_ = rsctrl.system.System.ResponseSystemStatus.NetCode.BAD_UNKNOWN;
        onChanged();
        return this;
      }
      
      // required .rsctrl.core.Bandwidth bw_total = 5;
      private rsctrl.core.Core.Bandwidth bwTotal_ = rsctrl.core.Core.Bandwidth.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          rsctrl.core.Core.Bandwidth, rsctrl.core.Core.Bandwidth.Builder, rsctrl.core.Core.BandwidthOrBuilder> bwTotalBuilder_;
      public boolean hasBwTotal() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public rsctrl.core.Core.Bandwidth getBwTotal() {
        if (bwTotalBuilder_ == null) {
          return bwTotal_;
        } else {
          return bwTotalBuilder_.getMessage();
        }
      }
      public Builder setBwTotal(rsctrl.core.Core.Bandwidth value) {
        if (bwTotalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bwTotal_ = value;
          onChanged();
        } else {
          bwTotalBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setBwTotal(
          rsctrl.core.Core.Bandwidth.Builder builderForValue) {
        if (bwTotalBuilder_ == null) {
          bwTotal_ = builderForValue.build();
          onChanged();
        } else {
          bwTotalBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeBwTotal(rsctrl.core.Core.Bandwidth value) {
        if (bwTotalBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              bwTotal_ != rsctrl.core.Core.Bandwidth.getDefaultInstance()) {
            bwTotal_ =
              rsctrl.core.Core.Bandwidth.newBuilder(bwTotal_).mergeFrom(value).buildPartial();
          } else {
            bwTotal_ = value;
          }
          onChanged();
        } else {
          bwTotalBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearBwTotal() {
        if (bwTotalBuilder_ == null) {
          bwTotal_ = rsctrl.core.Core.Bandwidth.getDefaultInstance();
          onChanged();
        } else {
          bwTotalBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public rsctrl.core.Core.Bandwidth.Builder getBwTotalBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getBwTotalFieldBuilder().getBuilder();
      }
      public rsctrl.core.Core.BandwidthOrBuilder getBwTotalOrBuilder() {
        if (bwTotalBuilder_ != null) {
          return bwTotalBuilder_.getMessageOrBuilder();
        } else {
          return bwTotal_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          rsctrl.core.Core.Bandwidth, rsctrl.core.Core.Bandwidth.Builder, rsctrl.core.Core.BandwidthOrBuilder> 
          getBwTotalFieldBuilder() {
        if (bwTotalBuilder_ == null) {
          bwTotalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              rsctrl.core.Core.Bandwidth, rsctrl.core.Core.Bandwidth.Builder, rsctrl.core.Core.BandwidthOrBuilder>(
                  bwTotal_,
                  getParentForChildren(),
                  isClean());
          bwTotal_ = null;
        }
        return bwTotalBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:rsctrl.system.ResponseSystemStatus)
    }
    
    static {
      defaultInstance = new ResponseSystemStatus(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rsctrl.system.ResponseSystemStatus)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rsctrl_system_RequestSystemStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rsctrl_system_RequestSystemStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rsctrl_system_ResponseSystemStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rsctrl_system_ResponseSystemStatus_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014system.proto\022\rrsctrl.system\032\ncore.prot" +
      "o\"\025\n\023RequestSystemStatus\"\366\002\n\024ResponseSys" +
      "temStatus\022#\n\006status\030\001 \002(\0132\023.rsctrl.core." +
      "Status\022\020\n\010no_peers\030\002 \002(\r\022\024\n\014no_connected" +
      "\030\003 \002(\r\022?\n\nnet_status\030\004 \002(\0162+.rsctrl.syst" +
      "em.ResponseSystemStatus.NetCode\022(\n\010bw_to" +
      "tal\030\005 \002(\0132\026.rsctrl.core.Bandwidth\"\245\001\n\007Ne" +
      "tCode\022\017\n\013BAD_UNKNOWN\020\000\022\017\n\013BAD_OFFLINE\020\001\022" +
      "\016\n\nBAD_NATSYM\020\002\022\021\n\rBAD_NODHT_NAT\020\003\022\023\n\017WA" +
      "RNING_RESTART\020\004\022\022\n\016WARNING_NATTED\020\005\022\021\n\rW",
      "ARNING_NODHT\020\006\022\010\n\004GOOD\020\007\022\017\n\013ADV_FORWARD\020" +
      "\010*.\n\rRequestMsgIds\022\035\n\031MsgId_RequestSyste" +
      "mStatus\020\001*0\n\016ResponseMsgIds\022\036\n\032MsgId_Res" +
      "ponseSystemStatus\020\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rsctrl_system_RequestSystemStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rsctrl_system_RequestSystemStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rsctrl_system_RequestSystemStatus_descriptor,
              new java.lang.String[] { },
              rsctrl.system.System.RequestSystemStatus.class,
              rsctrl.system.System.RequestSystemStatus.Builder.class);
          internal_static_rsctrl_system_ResponseSystemStatus_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rsctrl_system_ResponseSystemStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rsctrl_system_ResponseSystemStatus_descriptor,
              new java.lang.String[] { "Status", "NoPeers", "NoConnected", "NetStatus", "BwTotal", },
              rsctrl.system.System.ResponseSystemStatus.class,
              rsctrl.system.System.ResponseSystemStatus.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rsctrl.core.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
