/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_retroshare_android_bitdht */

#ifndef _Included_org_retroshare_android_bitdht
#define _Included_org_retroshare_android_bitdht
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_retroshare_android_bitdht
 * Method:    getIp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_retroshare_android_bitdht_getIp
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
