/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_retroshare_remote_bitdht */

#ifndef _Included_com_example_retroshare_remote_bitdht
#define _Included_com_example_retroshare_remote_bitdht
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_retroshare_remote_bitdht
 * Method:    getIp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_retroshare_remote_bitdht_getIp
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
